### ISSUE TITLE
Constant differences

### ISSUE THREAD

**Issue by worksofliam** [sitemule/noxDB#23]
What is the difference between these two constants?

* `JX_VALUE`
* `JX_LITERAL`

I am guessing one is for numbers/strings and the other booleans?

**Comment by NielsLiisberg** [comment]
Literals are straight letters as is - no escape . Typically used for:

     true false null 0 1 2 3 4 5 6 7 8 9 .

This can also be used for binary string that is normally not supported in
JSON

"values" are basically strings and will be escaped when used.

ex.

json_setvalue (pJson : 'example' : 'true' : JSON_LITERAL);
{
   "example" : true
}

json_setvalue (pJson : 'example' : 'true' : JSON_VALUE);
{
   "example" : "true"
}
