### ISSUE TITLE
Not Able to compile Samples for NoxDB with gmake 

### ISSUE THREAD

**Issue by ITMentalist** [sitemule/noxDB#24]
Hi Niels, 

I am getting the following error when trying to compile with gmake: 

CPD0011:  Qualifier missing from qualified name 'NOXDB     '.
CPF0001:  Error found on *N command.
gmake: *** [makefile:12: compile] Error 1

fill screenshot as below: 
![image](https://user-images.githubusercontent.com/5381496/86613729-49b67680-bfb2-11ea-960d-a191000d7e49.png)

Any noxdb compiles as per normal, 

Any help will greatly be appreciated to troubleshoot further. 

Regards
Marius

**Comment by BrianGarland** [comment]
Not Niels, but I have some good experience with the project.  

I am pretty sure you have to pass in the source file name you want to compile.  
i.e. `gmake jsonsql20.rpgle`

Although when I try that I get "Nothing to be done for ..."

**Comment by ITMentalist** [comment]
Hi Brian, 

Thank you for the feedback. I have also tried the same as you suggested, no luck. 

I can manually compile it on the outside by native commands though.

**Comment by ITMentalist** [comment]
I think I am going to close this as an issue.

**Comment by NielsLiisberg** [comment]
We are actually moving the examples into a more up-to-date state and right now we are using the vsCode compile feature thats sendt the OBJ / LIB and streamfile to the make procedure. So there is an issue - and we are working on it !!

**Comment by ITMentalist** [comment]
Thanks Niels. 

Looking forward to it.

**Comment by NielsLiisberg** [comment]
Gents;

Now the compile of examples works smoothly: Notice the name of the source where the first part up-until the first dot will be the object name. Next part is just text and is omitted. Finally, the extension that controls which compiler kicks in.
 

**Compile current file**
ssh -t myIBMi 'PATH=/QOpenSys/pkgs/bin:$PATH;cd /prj/noxDB/;gmake current SRC=${fileBasenameNoExtension}'

**Compile Service program noxDB**
ssh myIBMi 'PATH=/QOpenSys/pkgs/bin:$PATH;cd /prj/noxDB/;gmake all

**Compile Test modules for noxDB**
ssh myIBMi 'PATH=/QOpenSys/pkgs/bin:$PATH;cd /prj/noxDB/test/;gmake

**Compile current example file**
ssh -t myIBMi 'PATH=/QOpenSys/pkgs/bin:$PATH;cd /prj/noxDB/examples/;gmake compile SRC=${fileBasename} OBJ=${fileBasenameNoExtension
