### ISSUE TITLE
Tracing options?

### ISSUE THREAD

**Issue by wimjongman** [sitemule/noxDB#25]
I saw the trace.clle and it looks like it does SQL tracing, according to the name. 

Is there a way to trace the parsing process?

**Comment by NielsLiisberg** [comment]
There is not a tracing feature in the parser it self, however each time you access the object graph it will run pass a function

**jx_traceNode()**

if  you in the debugger change the variable it will dump each node:

eval debugger = 1
will create a trace file in /tmp

eval debugger = 2
will put the object or value on stdout

eval debugger = 3
will put the object or value in the joblog


The code goes like this: 

`if (debugger == 1) {
      sprintf(filename, "/tmp/jsonxml-%05.5d.json" , i ++);
      jx_WriteJsonStmf (pNode, filename , 1208, OFF, NULL);
   } else if (debugger == 2) {
      UCHAR temp [65536];
      int l = jx_AsJsonTextMem (pNode , temp , sizeof(temp));
      temp [l] = 0;
      puts (text);
      puts (temp);
      puts ("\n");
   } else if (debugger == 3) {
      jx_joblog ((PUCHAR) pNode);
   }
`

**Comment by wimjongman** [comment]
Skidegod!
