### ISSUE TITLE
Regression since e708612

### ISSUE THREAD

**Issue by wimjongman** [sitemule/noxDB#28]
Commit [e708612](https://github.com/sitemule/noxDB/commit/e708612b057c7d3818ac3057bbc3c1d8fa76ae4e) introduced a regression. 

When building noxDB with this commit, the Json_GetStr procedure returns blanks.
When building NoxDB with the previous commit [f0a1e75](f0a1e752e7ab12932f511bccd5302ceb144d14f5) the procedure works fine.

I will provide my example in a pull request.

**Comment by NielsLiisberg** [comment]
We are having some issue with different use of ccsid’s. So my guess is it works if you set your ccsid to 500 befor doing the regression test. I am sorry for the inconvinience but i have to make it work on all (if possible ) ccsids .. so this is kind of work in progress. There is anothe branche  on this github site where the object graph and all access to it is 100% utf-8 which is the Way to go, however so many is already using this Master so i have to do some work for alle the EBCDIC version as well. Thank you for the input . And until the use the commit that works for you.

**Comment by wimjongman** [comment]
Ok, the UTF8 branch sounds great. I will give that a spin as well.
