### ISSUE TITLE
json_sqlGetInsertId should use Big Integer

### ISSUE THREAD

**Issue by mlitters** [sitemule/noxDB#33]
The json_sqlGetInsertId uses an Integer Variable as return value.
For many tables this is not big enough.
Can you please change or overload it with a big Integer?

**Comment by ottersberg** [comment]
same with json_SetInt.

**Comment by NielsLiisberg** [comment]
Good point. It is on the list..

tor. 3. jun. 2021 kl. 18.00 skrev Jens Ottersberg ***@***.***

**Comment by NielsLiisberg** [comment]
This is fixed along with getInt and setInt. It is backward compatible and after recompile of the client application it will point the new new versions where all are int(20)  ( that is 64 signed bit)
