### ISSUE TITLE
Debug when you want with something like json_debug()

### ISSUE THREAD

**Issue by ottersberg** [sitemule/noxDB#34]
As shown in Issue #25 there are options for debugging.
But you are dependent on when a noxDB function gets there.
With a function like json_debug(pNode) which links to jx_traceNode() you could decide when you want to debug something.

**Comment by NielsLiisberg** [comment]
Yes! I am working on a solution where you can register your own trace
callback function - that might be a procedure in your current code or a
service program of your own. And I will provide an example..

Thanx for a great idea!!

tor. 3. jun. 2021 kl. 18.06 skrev Jens Ottersberg ***@***.***

**Comment by ottersberg** [comment]
Ah okay. Didn't know that Issue #32 includes also an option for user-defined calls so that you can call it whenever you want.

**Comment by NielsLiisberg** [comment]
No it is not clear- however that is my interpretation of what makes most
sense. Perhaps we should rename this issue. What do you think?


lør. 5. jun. 2021 kl. 12.25 skrev Jens Ottersberg ***@***.***

**Comment by ottersberg** [comment]
Of course. Feel free to rename.

**Comment by NielsLiisberg** [comment]
I hope this issues is also fixed by #32 - otherwise please reopen the issue if that is not exactly what you were asking for.
