### ISSUE TITLE
Node where the key includes alternative separator is not located

### ISSUE THREAD

**Issue by m1h43l** [sitemule/noxDB#52]
`{ "area.code" : "32452" }` cannot be located with the point character as a separator. `jx_locate(json : '.area.code');` fails to locate the node. If this is intended we should document it somewhere.

Unit test NOXDBUT3 test case TEST_KEY_WITH_ALTERNATIVE_ELEMENT_SEPARATOR_ABSOLUTE .

**Comment by m1h43l** [comment]
Same also don't work for the "normal" path separator character, forward slash / .

**Comment by NielsLiisberg** [comment]
Works as designed - the dot has the same function ad the forward slash: If you need alternative chars then change the delimiters. See examples:

./noxDB/examples/JSONPARS2E.JSON-Parse-String-names-with-dots.rpgle
