### ISSUE TITLE
Cannot build due to invalid data in QRNTYPES

### ISSUE THREAD

**Issue by worksofliam** [sitemule/noxDB#58]
See here: https://github.com/sitemule/noxDB/blob/master/headers/qoar/h/qrntypes

**Comment by worksofliam** [comment]
To fix:

1. `rm -rf ./headers/qoar/h`
2. `gmake link`

Perhaps those files need to be removed from the repo and added to the .gitignore?

**Comment by worksofliam** [comment]
PR incoming in a few hours.

**Comment by NielsLiisberg** [comment]
Year  -but this is trixy: Dependent on the OS version. There is no silver
bullet for this one - Look in the make file. There is a flag for this !!

**Comment by NielsLiisberg** [comment]
I have don the pull request, Now it fails to build on 7.2 - I'll have to find a better way

**Comment by NielsLiisberg** [comment]
I have don the pull request, Now it fails to build on 7.2 - I'll have to find a better way
