### ISSUE TITLE
How to set null value in noxdb 2?

### ISSUE THREAD

**Issue by m1h43l** [sitemule/noxDB#62]
I couldn't find a function which sets null as a value. How to generate the following JSON with noxDB 2: 
```
{ "error" : null }
```

**Comment by NielsLiisberg** [comment]
look for :

json_setNull(pNode);

**Comment by m1h43l** [comment]
That would have also be my first guess. But there is no prototype for `nox_setNull` nor `json_setNull` and there is no exported function `nox_setNull` (in noxDB2.binder).

**Comment by NielsLiisberg** [comment]
I think you need to pull:

///
// Set node with null value
//
// Creates a node at the passed path with the value <code>*null</code>.
// Any existing node will be replaced by this new node.
//
// @param Node
// @param Node path expression
// @return New node
///
Dcl-PR jx_setNull pointer extproc(*CWIDEN : 'jx_SetNullByName');
  node pointer value;
  nodePath pointer value options(*string);
End-PR;

**Comment by m1h43l** [comment]
But that is noxDB 1 ... I am searching for a `setNull` function on the `utf8` branch.

**Comment by NielsLiisberg** [comment]
True; it's missing

**Comment by NielsLiisberg** [comment]
Done!!
