### ISSUE TITLE
Numeric 30:15 not quite large enough

### ISSUE THREAD

**Issue by wimjongman** [sitemule/noxDB#79]
We are trying to operate on packed(20:2) numbers that do not fit setNum. Setnum operates on 30:15. Is there a solution other than converting the large number to a string?

Would it be as simple as changing setNum to 40:15?

**Comment by NielsLiisberg** [comment]
It was for historic reasons;

The max size was the 30

But you can simply do like in
examples/JSONPARS2G.JSON-Append-using-NodeAdd.rpgle

pmy20_2 = json_NodeAdd(pNode:json_AFTER_SIBLING:'mybrother': %char(my20_2)
: json_LITERAL);

Perhaps not elegant. and you need to have the edit code set to '.'  or use
%EDIT.

Internal noxDb stores  everything in plain char sequence to not have any
limitations of sizes nor decimals . ..

.. There will come a version using the new *CONVERT making this go away ...

**Comment by wimjongman** [comment]
Ok, thanks for the hint. I can work with that.
