### ISSUE TITLE
noxDB vesrsion seems to be missing

### ISSUE THREAD

**Issue by krka01** [sitemule/noxDB#89]
Hi,

I can not find any form of versions in noxDB. I think there is a need for some kind of version description.

Thanks

**Comment by NielsLiisberg** [comment]
noxDb ( and ILEastic and ILEvator) has a promise to always be backward
compatible. Therefore the version is more or less the git commit. So always
pull the main branch.

**Comment by krka01** [comment]
@NielsLiisberg Thanks for the reply. I do understand what you are saying. 

We have starting to explore the possibilities with noxDB at my company, but a concern have been raised how we can identify which version we have installed on every single IBM i partition.

Besides the built date, the only way I have found to identify this, is be looking at the COPYRIGHT_STRING with the SQL service QSYS2.PROGRAM_INFO as it have the git checkout commit listed there.  

Is there any other, better way to identify the installed version? 

The only concern I have with using the git commit as a version, is that you can not tell by just looking at the commit string to differentiate which is newest without heading to the sitemule/noxDB commits and search for them.

**Comment by krka01** [comment]
@NielsLiisberg I think it should be sufficient if you could also append the date and time for the git commit in the copyright string.

**Comment by NielsLiisberg** [comment]
This sounds like a great idea. Will do!!

man. 9. sep. 2024 kl. 09.00 skrev Krister Karlsson ***@***.***
