### ISSUE TITLE
Prototypes missing from JSONXML.rpgle

### ISSUE THREAD

**Issue by WorksOfLiam** [sitemule/noxDB#9]
Because `jx_GetInt` is not a real function, it is not defined in the `JSONXML.rpgle` header.

It was previously defined in the `JSONPARSER.rpgle`, before we made a new one generate every time the makefile was called.

You can see that here: https://github.com/sitemule/noxDB/blob/b3a15fea9dfd7786d4def41eda8facde5b878ebd/headers/JSONPARSER.rpgle#L325

Looks like we just need to add the following headers from the previous version of `JSONPARSER.rpgle` to `JSONXML.rpgle` and also rename the namespace to use `jx_`.

This has to be done with the following API:

* `json_getInt` - https://github.com/sitemule/noxDB/blob/b3a15fea9dfd7786d4def41eda8facde5b878ebd/headers/JSONPARSER.rpgle#L325

* `json_httprequest` - https://github.com/sitemule/noxDB/blob/b3a15fea9dfd7786d4def41eda8facde5b878ebd/headers/JSONPARSER.rpgle#L839

* `json_memuse` - https://github.com/sitemule/noxDB/blob/b3a15fea9dfd7786d4def41eda8facde5b878ebd/headers/JSONPARSER.rpgle#L691

* `json_clear` - https://github.com/sitemule/noxDB/blob/b3a15fea9dfd7786d4def41eda8facde5b878ebd/headers/JSONPARSER.rpgle#L671

* `JSON_ARRAYAPPEND` - https://github.com/sitemule/noxDB/blob/b3a15fea9dfd7786d4def41eda8facde5b878ebd/headers/JSONPARSER.rpgle#L671

* `JSON_ARRAYSLICE` https://github.com/sitemule/noxDB/blob/b3a15fea9dfd7786d4def41eda8facde5b878ebd/headers/JSONPARSER.rpgle#L437

* `json_AsJsonTextMem` - missing last parameter - https://github.com/sitemule/noxDB/blob/b3a15fea9dfd7786d4def41eda8facde5b878ebd/headers/JSONPARSER.rpgle#L526

* `JSON_COPYVALUE` - https://github.com/sitemule/noxDB/blob/b3a15fea9dfd7786d4def41eda8facde5b878ebd/headers/JSONPARSER.rpgle#L338

* `JSON_USE_LOCALE` const - https://github.com/sitemule/noxDB/blob/b3a15fea9dfd7786d4def41eda8facde5b878ebd/headers/JSONPARSER.rpgle#L457

* `json_NodeCheckSum` - https://github.com/sitemule/noxDB/blob/b3a15fea9dfd7786d4def41eda8facde5b878ebd/headers/JSONPARSER.rpgle#L395

* `json_traceSetId` - https://github.com/sitemule/noxDB/blob/b3a15fea9dfd7786d4def41eda8facde5b878ebd/headers/JSONPARSER.rpgle#L847

* `JSON_APPROXIMATE_TOTALROWS` const - https://github.com/sitemule/noxDB/blob/b3a15fea9dfd7786d4def41eda8facde5b878ebd/headers/JSONPARSER.rpgle#L751

* `xml_SetAttrValue` - missing new parameter

> The originals a now in DKSRV206/JSONXML/QRPGLESRC

**Comment by WorksOfLiam** [comment]
Hi! All the new prototypes and consts have been pushed up to my fork, which I will make a PR for today.

The last issue is that the examples show xml_SetAttrValue having 3 parameters, but our prototypes only have two.

```
        xml_SetAttrValue(pt    : 'MyAttribute' : 'First value');
        xml_SetAttrValue(pt    : 'MyAttribute' : 'New Value');
        xml_SetAttrValue(pt    : 'a2'          : 'a2 1');
        xml_SetAttrValue(pt    : 'a2'          : 'a2 2');
```

I have tried searching old sources for the definition:

```
> FNDSTRPDM STRING(SETATTRVALUE) FILE(NOXDB/QSRC) MBR(*ALL) OPTION(*DSP)  
  0 members match the Find string in file QSRC.                           
> FNDSTRPDM STRING(SETATTRVALUE) FILE(JSONXML/QSRC) MBR(*ALL) OPTION(*DSP)
  0 members match the Find string in file QSRC.                           
```

I also tried searching the local repo, but nothing but examples come up:

![image](https://user-images.githubusercontent.com/3708366/45355998-f5126200-b5b9-11e8-82b7-6484d0c06893.png)

This is the last pressing issue before a PR can be made.

Thanks,
Liam Barry

**Comment by NielsLiisberg** [comment]
You are looking in a file you have replaced: The original before you began is stored in library JSONXMLORG

![image](https://user-images.githubusercontent.com/2787230/47004160-3655de80-d131-11e8-8133-950e7b7d05c4.png)
